/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagentesinteligentes.gui;

import com.mycompany.sistemaagentesinteligentes.model.AgenteAsistenciaMedica;
import com.mycompany.sistemaagentesinteligentes.services.ServicioAgentes;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Acuña, Luis Hernández, Stephany Trujillo
 */
public class GUIAdicionarAsistenciaMedica extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIAdicionarAsistenciaMedica.class.getName());

    /**
     * Creates new form GUIAdicionarAsistenciaMedica
     */
    public GUIAdicionarAsistenciaMedica() {
        setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAgente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNivelAutonomia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEstadoOperativo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNivelConfianza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsuarioAsignado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoAsistencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNivelUrgencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtComandosProcesados = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdiomaRespuesta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEspecialidadMedica = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNivelPrioridadPaciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtProtocoloEmergencia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSignosVitalesMonitoreados = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTiempoRespuestaMedica = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUIAdicionarAsistenciaMedica");

        jPanel1.setBackground(new java.awt.Color(21, 101, 192));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar Agente de Asistencia Medica");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Agente");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nivel de Autonomia (0-100)");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado Operativo (ACTIVO/INACTIVO/MANTENIMIENTO)");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nivel de Confianza (0-100)");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario Asignado");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Asistencia");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nivel de Urgencia (1-5)");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Comandos Procesados");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Idioma de Respuesta");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Especialidad Medica");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nivel Prioridad Paciente (1-5)");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Protocolo de Emergencia (true/false)");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Signos Vitales Monitoreados");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tiempo Respuesta Medica (min)");

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setForeground(new java.awt.Color(21, 101, 192));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                        )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivelAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivelConfianza, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivelUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComandosProcesados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdiomaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspecialidadMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivelPrioridadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProtocoloEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSignosVitalesMonitoreados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoRespuestaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                    )
                    .addComponent(btnAdicionar)
                )
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNivelAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstadoOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNivelConfianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsuarioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTipoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNivelUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtComandosProcesados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdiomaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEspecialidadMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNivelPrioridadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtProtocoloEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSignosVitalesMonitoreados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTiempoRespuestaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            String strIdAgente = txtIdAgente.getText().trim();
            int idAgente = Integer.parseInt(strIdAgente);
            String strNombre = txtNombre.getText().trim();
            String nombre = strNombre;
            String strNivelAutonomia = txtNivelAutonomia.getText().trim();
            double nivelAutonomia = Double.parseDouble(strNivelAutonomia);
            String strEstadoOperativo = txtEstadoOperativo.getText().trim();
            String estadoOperativo = strEstadoOperativo;
            String strNivelConfianza = txtNivelConfianza.getText().trim();
            double nivelConfianza = Double.parseDouble(strNivelConfianza);
            String strUsuarioAsignado = txtUsuarioAsignado.getText().trim();
            String usuarioAsignado = strUsuarioAsignado;
            String strTipoAsistencia = txtTipoAsistencia.getText().trim();
            String tipoAsistencia = strTipoAsistencia;
            String strNivelUrgencia = txtNivelUrgencia.getText().trim();
            int nivelUrgencia = Integer.parseInt(strNivelUrgencia);
            String strComandosProcesados = txtComandosProcesados.getText().trim();
            int comandosProcesados = Integer.parseInt(strComandosProcesados);
            String strIdiomaRespuesta = txtIdiomaRespuesta.getText().trim();
            String idiomaRespuesta = strIdiomaRespuesta;
            String strEspecialidadMedica = txtEspecialidadMedica.getText().trim();
            String especialidadMedica = strEspecialidadMedica;
            String strNivelPrioridadPaciente = txtNivelPrioridadPaciente.getText().trim();
            int nivelPrioridadPaciente = Integer.parseInt(strNivelPrioridadPaciente);
            String strProtocoloEmergencia = txtProtocoloEmergencia.getText().trim();
            boolean protocoloEmergencia = Boolean.parseBoolean(strProtocoloEmergencia);
            String strSignosVitalesMonitoreados = txtSignosVitalesMonitoreados.getText().trim();
            int signosVitalesMonitoreados = Integer.parseInt(strSignosVitalesMonitoreados);
            String strTiempoRespuestaMedica = txtTiempoRespuestaMedica.getText().trim();
            double tiempoRespuestaMedica = Double.parseDouble(strTiempoRespuestaMedica);

            if (ServicioAgentes.obtenerAgente(idAgente) != null) {
                JOptionPane.showMessageDialog(this, "Error: Ya existe un agente registrado con el ID " + idAgente, "ID Duplicado", JOptionPane.WARNING_MESSAGE);
                return;
            }

            AgenteAsistenciaMedica ag = new AgenteAsistenciaMedica(idAgente, nombre, nivelAutonomia, estadoOperativo, nivelConfianza,
                    usuarioAsignado, tipoAsistencia, nivelUrgencia, comandosProcesados, idiomaRespuesta,
                    especialidadMedica, nivelPrioridadPaciente, protocoloEmergencia, signosVitalesMonitoreados, tiempoRespuestaMedica);
            ServicioAgentes.addAgente(ag);
            JOptionPane.showMessageDialog(this, "Agente de asistencia medica creado!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: revisa que el ID y los demas campos numericos (autonomia, confianza, urgencia, comandos procesados, prioridad, signos vitales, tiempo de respuesta) sean numeros validos.", "Dato invalido", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "No se pudo crear el agente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new GUIAdicionarAsistenciaMedica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIdAgente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNivelAutonomia;
    private javax.swing.JTextField txtEstadoOperativo;
    private javax.swing.JTextField txtNivelConfianza;
    private javax.swing.JTextField txtUsuarioAsignado;
    private javax.swing.JTextField txtTipoAsistencia;
    private javax.swing.JTextField txtNivelUrgencia;
    private javax.swing.JTextField txtComandosProcesados;
    private javax.swing.JTextField txtIdiomaRespuesta;
    private javax.swing.JTextField txtEspecialidadMedica;
    private javax.swing.JTextField txtNivelPrioridadPaciente;
    private javax.swing.JTextField txtProtocoloEmergencia;
    private javax.swing.JTextField txtSignosVitalesMonitoreados;
    private javax.swing.JTextField txtTiempoRespuestaMedica;
    // End of variables declaration//GEN-END:variables
}
