/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagentesinteligentes.gui;

import com.mycompany.sistemaagentesinteligentes.model.AgenteInteligente;
import com.mycompany.sistemaagentesinteligentes.model.AgenteAsistenciaMedica;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sistemaagentesinteligentes.services.IServicioAgentes;
import com.mycompany.sistemaagentesinteligentes.services.ServicioAgentes;
import com.mycompany.sistemaagentesinteligentes.services.ServicioObserver;

/**
 *
 * @author Juan Acuña, Luis Hernández, Stephany Trujillo
 */
public class GUIListarAsistenciaMedica extends javax.swing.JFrame implements ICambiable {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIListarAsistenciaMedica.class.getName());

    private IServicioAgentes servicioAgentes;

    /**
     * Creates new form GUIListarAsistenciaMedica
     */
    public GUIListarAsistenciaMedica() {
        initComponents();
        setLocationRelativeTo(null);
        servicioAgentes = ServicioAgentes.getInstancia();
        ServicioObserver.addGUIAgente(this);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                ServicioObserver.delGUIAgente(GUIListarAsistenciaMedica.this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgentes = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUIListarAsistenciaMedica");

        jPanel1.setBackground(new java.awt.Color(21, 101, 192));

        tblAgentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Autonomia", "Estado", "Confianza", "Usuario", "Tipo Asist.", "Urgencia", "Comandos", "Idioma", "Especialidad", "Prioridad Pac.", "Protoc. Emerg.", "Signos Vitales", "Tiempo Resp."
            }
        ));
        jScrollPane1.setViewportView(tblAgentes);

        btnListar.setBackground(new java.awt.Color(255, 255, 255));
        btnListar.setForeground(new java.awt.Color(21, 101, 192));
        btnListar.setText("Listar");
        btnListar.addActionListener(this::btnListarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnListarActionPerformed

    private void cargarTabla() {
        Map<Integer, AgenteInteligente> agentes = servicioAgentes.getAgentes();

        DefaultTableModel modelo = (DefaultTableModel) tblAgentes.getModel();
        modelo.setRowCount(0);
        for (Map.Entry<Integer, AgenteInteligente> entrada : agentes.entrySet()) {
            if (!(entrada.getValue() instanceof AgenteAsistenciaMedica)) {
                continue;
            }
            AgenteAsistenciaMedica ag = (AgenteAsistenciaMedica) entrada.getValue();

            Object[] fila = new Object[]{
                ag.getIdAgente(),
                ag.getNombre(),
                ag.getNivelAutonomia(),
                ag.getEstadoOperativo(),
                ag.getNivelConfianza(),
                ag.getUsuarioAsignado(),
                ag.getTipoAsistencia(),
                ag.getNivelUrgencia(),
                ag.getComandosProcesados(),
                ag.getIdiomaRespuesta(),
                ag.getEspecialidadMedica(),
                ag.getNivelPrioridadPaciente(),
                ag.isProtocoloEmergencia(),
                ag.getSignosVitalesMonitoreados(),
                ag.getTiempoRespuestaMedica()
            };

            modelo.addRow(fila);
        }
    }

    @Override
    public void cambio() {
        cargarTabla();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new GUIListarAsistenciaMedica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgentes;
    // End of variables declaration//GEN-END:variables
}
