/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaagentesinteligentes.gui;

import com.mycompany.sistemaagentesinteligentes.services.InformacionAplicacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Acuña, Luis Hernández, Stephany Trujillo
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuAgenteNavegacion = new javax.swing.JMenu();
        menuItemAdicionarNavegacion = new javax.swing.JMenuItem();
        menuItemListarNavegacion = new javax.swing.JMenuItem();
        menuItemConsultarNavegacion = new javax.swing.JMenuItem();
        menuItemActualizarNavegacion = new javax.swing.JMenuItem();
        menuItemEliminarNavegacion = new javax.swing.JMenuItem();
        menuAgenteAsistenciaMedica = new javax.swing.JMenu();
        menuItemAdicionarAsistenciaMedica = new javax.swing.JMenuItem();
        menuItemListarAsistenciaMedica = new javax.swing.JMenuItem();
        menuItemConsultarAsistenciaMedica = new javax.swing.JMenuItem();
        menuItemActualizarAsistenciaMedica = new javax.swing.JMenuItem();
        menuItemEliminarAsistenciaMedica = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuItemAdicionarUsuario = new javax.swing.JMenuItem();
        menuItemListarUsuario = new javax.swing.JMenuItem();
        menuItemActualizarUsuario = new javax.swing.JMenuItem();
        menuItemEliminarUsuario = new javax.swing.JMenuItem();
        menuCalculos = new javax.swing.JMenu();
        menuItemCalcularRendimiento = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAutores = new javax.swing.JMenuItem();
        menuItemComoUsarlo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUIPrincipal");

        jPanel1.setBackground(new java.awt.Color(21, 101, 192));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE AGENTES INTELIGENTES");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestiona agentes de navegacion, agentes de asistencia y agentes de asistencia medica.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(this::menuItemSalirActionPerformed);
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuAgenteNavegacion.setText("AgenteNavegacion");

        menuItemAdicionarNavegacion.setText("Adicionar AgenteNavegacion");
        menuItemAdicionarNavegacion.addActionListener(this::menuItemAdicionarNavegacionActionPerformed);
        menuAgenteNavegacion.add(menuItemAdicionarNavegacion);

        menuItemListarNavegacion.setText("Listar AgenteNavegacion");
        menuItemListarNavegacion.addActionListener(this::menuItemListarNavegacionActionPerformed);
        menuAgenteNavegacion.add(menuItemListarNavegacion);

        menuItemConsultarNavegacion.setText("Consultar AgenteNavegacion");
        menuItemConsultarNavegacion.addActionListener(this::menuItemConsultarNavegacionActionPerformed);
        menuAgenteNavegacion.add(menuItemConsultarNavegacion);

        menuItemActualizarNavegacion.setText("Actualizar AgenteNavegacion");
        menuItemActualizarNavegacion.addActionListener(this::menuItemActualizarNavegacionActionPerformed);
        menuAgenteNavegacion.add(menuItemActualizarNavegacion);

        menuItemEliminarNavegacion.setText("Eliminar AgenteNavegacion");
        menuItemEliminarNavegacion.addActionListener(this::menuItemEliminarNavegacionActionPerformed);
        menuAgenteNavegacion.add(menuItemEliminarNavegacion);

        jMenuBar1.add(menuAgenteNavegacion);

        menuAgenteAsistenciaMedica.setText("AgenteAsistenciaMedica");

        menuItemAdicionarAsistenciaMedica.setText("Adicionar AgenteAsistenciaMedica");
        menuItemAdicionarAsistenciaMedica.addActionListener(this::menuItemAdicionarAsistenciaMedicaActionPerformed);
        menuAgenteAsistenciaMedica.add(menuItemAdicionarAsistenciaMedica);

        menuItemListarAsistenciaMedica.setText("Listar AgenteAsistenciaMedica");
        menuItemListarAsistenciaMedica.addActionListener(this::menuItemListarAsistenciaMedicaActionPerformed);
        menuAgenteAsistenciaMedica.add(menuItemListarAsistenciaMedica);

        menuItemConsultarAsistenciaMedica.setText("Consultar AgenteAsistenciaMedica");
        menuItemConsultarAsistenciaMedica.addActionListener(this::menuItemConsultarAsistenciaMedicaActionPerformed);
        menuAgenteAsistenciaMedica.add(menuItemConsultarAsistenciaMedica);

        menuItemActualizarAsistenciaMedica.setText("Actualizar AgenteAsistenciaMedica");
        menuItemActualizarAsistenciaMedica.addActionListener(this::menuItemActualizarAsistenciaMedicaActionPerformed);
        menuAgenteAsistenciaMedica.add(menuItemActualizarAsistenciaMedica);

        menuItemEliminarAsistenciaMedica.setText("Eliminar AgenteAsistenciaMedica");
        menuItemEliminarAsistenciaMedica.addActionListener(this::menuItemEliminarAsistenciaMedicaActionPerformed);
        menuAgenteAsistenciaMedica.add(menuItemEliminarAsistenciaMedica);

        jMenuBar1.add(menuAgenteAsistenciaMedica);

        menuUsuario.setText("Usuario (Gestionar D)");

        menuItemAdicionarUsuario.setText("Adicionar Usuario");
        menuItemAdicionarUsuario.addActionListener(this::menuItemAdicionarUsuarioActionPerformed);
        menuUsuario.add(menuItemAdicionarUsuario);

        menuItemListarUsuario.setText("Listar Usuario");
        menuItemListarUsuario.addActionListener(this::menuItemListarUsuarioActionPerformed);
        menuUsuario.add(menuItemListarUsuario);

        menuItemActualizarUsuario.setText("Actualizar Usuario");
        menuItemActualizarUsuario.addActionListener(this::menuItemActualizarUsuarioActionPerformed);
        menuUsuario.add(menuItemActualizarUsuario);

        menuItemEliminarUsuario.setText("Eliminar Usuario");
        menuItemEliminarUsuario.addActionListener(this::menuItemEliminarUsuarioActionPerformed);
        menuUsuario.add(menuItemEliminarUsuario);

        jMenuBar1.add(menuUsuario);

        menuCalculos.setText("Calculos");

        menuItemCalcularRendimiento.setText("Calcular Rendimiento");
        menuItemCalcularRendimiento.addActionListener(this::menuItemCalcularRendimientoActionPerformed);
        menuCalculos.add(menuItemCalcularRendimiento);

        jMenuBar1.add(menuCalculos);

        menuAyuda.setText("Ayuda");

        menuItemAutores.setText("Autores");
        menuItemAutores.addActionListener(this::menuItemAutoresActionPerformed);
        menuAyuda.add(menuItemAutores);

        menuItemComoUsarlo.setText("¿Como usarlo?");
        menuItemComoUsarlo.addActionListener(this::menuItemComoUsarloActionPerformed);
        menuAyuda.add(menuItemComoUsarlo);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemAdicionarNavegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdicionarNavegacionActionPerformed
        GUIAdicionarNavegacion gui = new GUIAdicionarNavegacion();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemAdicionarNavegacionActionPerformed

    private void menuItemListarNavegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarNavegacionActionPerformed
        GUIListarNavegacion gui = new GUIListarNavegacion();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemListarNavegacionActionPerformed

    private void menuItemAdicionarAsistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdicionarAsistenciaMedicaActionPerformed
        GUIAdicionarAsistenciaMedica gui = new GUIAdicionarAsistenciaMedica();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemAdicionarAsistenciaMedicaActionPerformed

    private void menuItemListarAsistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarAsistenciaMedicaActionPerformed
        GUIListarAsistenciaMedica gui = new GUIListarAsistenciaMedica();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemListarAsistenciaMedicaActionPerformed

    private void menuItemConsultarNavegacionActionPerformed(java.awt.event.ActionEvent evt) {
        GUIConsultarNavegacion gui = new GUIConsultarNavegacion();
        gui.setVisible(true);
    }

    private void menuItemEliminarNavegacionActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEliminarNavegacion gui = new GUIEliminarNavegacion();
        gui.setVisible(true);
    }

    private void menuItemConsultarAsistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {
        GUIConsultarAsistenciaMedica gui = new GUIConsultarAsistenciaMedica();
        gui.setVisible(true);
    }

    private void menuItemEliminarAsistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEliminarAsistenciaMedica gui = new GUIEliminarAsistenciaMedica();
        gui.setVisible(true);
    }

    private void menuItemActualizarNavegacionActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEditarNavegacion gui = new GUIEditarNavegacion();
        gui.setVisible(true);
    }

    private void menuItemActualizarAsistenciaMedicaActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEditarAsistenciaMedica gui = new GUIEditarAsistenciaMedica();
        gui.setVisible(true);
    }

    private void menuItemAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        GUIAdicionarUsuario gui = new GUIAdicionarUsuario();
        gui.setVisible(true);
    }

    private void menuItemListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        GUIListarUsuario gui = new GUIListarUsuario();
        gui.setVisible(true);
    }

    private void menuItemActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEditarUsuario gui = new GUIEditarUsuario();
        gui.setVisible(true);
    }

    private void menuItemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        GUIEliminarUsuario gui = new GUIEliminarUsuario();
        gui.setVisible(true);
    }

    private void menuItemCalcularRendimientoActionPerformed(java.awt.event.ActionEvent evt) {
        GUICalcularRendimiento gui = new GUICalcularRendimiento();
        gui.setVisible(true);
    }

    private void menuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAutoresActionPerformed
        InformacionAplicacion info = InformacionAplicacion.getInstancia();
        JOptionPane.showMessageDialog(null,
                info.getNombreAplicacion() + "\n"
                + "Integrantes: " + info.getIntegrantes() + "\n"
                + info.getVersion(),
                "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemAutoresActionPerformed

    private void menuItemComoUsarloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemComoUsarloActionPerformed
        JOptionPane.showMessageDialog(null, "Tienes un menu para gestionar dos tipos de agentes: Navegacion y Asistencia Medica.", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "AgenteNavegacion y AgenteAsistenciaMedica heredan directamente de AgenteInteligente. AgenteAsistenciaMedica reemplaza al antiguo AgenteAsistencia (ya incluye todos sus atributos).", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Puedes adicionar y listar cada tipo de agente desde su respectivo menu.", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Para consultar o eliminar un agente, escribe su ID en el campo de busqueda y presiona Consultar (o Enter).", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Los agentes se guardan en memoria mientras el programa esta abierto; al cerrarlo, la informacion no se conserva.", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemComoUsarloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAgenteAsistenciaMedica;
    private javax.swing.JMenu menuAgenteNavegacion;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCalculos;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem menuItemActualizarAsistenciaMedica;
    private javax.swing.JMenuItem menuItemActualizarNavegacion;
    private javax.swing.JMenuItem menuItemActualizarUsuario;
    private javax.swing.JMenuItem menuItemAdicionarAsistenciaMedica;
    private javax.swing.JMenuItem menuItemAdicionarNavegacion;
    private javax.swing.JMenuItem menuItemAdicionarUsuario;
    private javax.swing.JMenuItem menuItemAutores;
    private javax.swing.JMenuItem menuItemCalcularRendimiento;
    private javax.swing.JMenuItem menuItemComoUsarlo;
    private javax.swing.JMenuItem menuItemConsultarAsistenciaMedica;
    private javax.swing.JMenuItem menuItemConsultarNavegacion;
    private javax.swing.JMenuItem menuItemEliminarAsistenciaMedica;
    private javax.swing.JMenuItem menuItemEliminarNavegacion;
    private javax.swing.JMenuItem menuItemEliminarUsuario;
    private javax.swing.JMenuItem menuItemListarAsistenciaMedica;
    private javax.swing.JMenuItem menuItemListarNavegacion;
    private javax.swing.JMenuItem menuItemListarUsuario;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
